FROM node:18.12.1-alpine3.16 AS build

# LABEL Jeff Navarra "jeff.navarra@miapeer.com"

# # Install stuff
# RUN apk update
# RUN apk upgrade

# Install requirements
COPY . .
WORKDIR /miapeer
RUN npm install

# ENV ORIGIN=https://www.miapeer.com

# RUN ORIGIN=https://www.miapeer.com npm run build
RUN npm run build

# # https://sveltesociety.dev/recipes/publishing-and-deploying/dockerize-a-svelte-app
# # https://medium.com/@alpercitak/dockerize-sveltekit-1323771a12b1

# FROM nginx:1.23-alpine AS deploy

# WORKDIR /usr/share/nginx/html
# RUN rm -rf ./*
# COPY --from=build /app/build .

RUN echo \{\"lastUpdate\": \"`date +%Y.%m.%d-%H:%M:%S`\"\} > ./last_update.json

EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

# CMD ["ORIGIN=https://www.miapeer.com", "npm", "run", "preview", "--", "ORIGIN=https://www.miapeer.com", "--host", "0.0.0.0", "--port", "80"]
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "80"]
