FROM node:18.12.1-alpine3.16

# LABEL Jeff Navarra "jeff.navarra@miapeer.com"

# Install stuff
RUN apk update
RUN apk upgrade
RUN apk add bash

# Install requirements
COPY ./miapeer/package.json /miapeer/miapeer/package.json
COPY ./miapeer/package-lock.json /miapeer/miapeer/package-lock.json
WORKDIR /miapeer/miapeer
RUN npm install

# Do the thing
WORKDIR /miapeer

EXPOSE 8001

CMD ["npm", "run", "--prefix", "miapeer", "dev", "--", "--host"]
