FROM node:18.12.1-alpine3.16

# LABEL Jeff Navarra "jeff.navarra@miapeer.com"

# Install stuff
RUN apk update
RUN apk upgrade

# Install requirements
COPY ./miapeer/package.json /miapeer/miapeer/package.json
COPY ./miapeer/package-lock.json /miapeer/miapeer/package-lock.json
WORKDIR /miapeer/miapeer
RUN npm install

# https://sveltesociety.dev/recipes/publishing-and-deploying/dockerize-a-svelte-app
# https://medium.com/@alpercitak/dockerize-sveltekit-1323771a12b1
# RUN npm run build

WORKDIR /miapeer

EXPOSE 8001

CMD []
