on:
  push:
    branches:
      - main

name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Azure Container Registry Login"
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build and push Docker image"
        run: |
          docker image build --file ./Dockerfile-prod --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/miapeer .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/miapeer
