on: [push]
name: Linux_Container_Workflow

env:
  PUBLIC_MIAPEER_API_HOST: https://api.miapeer.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker image build --build-arg PUBLIC_MIAPEER_API_HOST=https://api.miapeer.com --file ./Dockerfile-prod --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/miapeer:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/miapeer:${{ github.sha }}
